import os


Import('env')



#VariantDir('../build-release','../src',duplicate= False)
source_files = Glob('../build-release/*.cc')
object_files = env.Object(source_files)
env.StaticLibrary('StringUtilities',object_files)

